// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pccMYD3rv65umzhXuKdgDp
// Component: Gno78PvNwzbz
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: pccMYD3rv65umzhXuKdgDp/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: Gno78PvNwzbz/css

import IconnavigationarrowDownward24PxIcon from "./icons/PlasmicIcon__IconnavigationarrowDownward24Px"; // plasmic-import: 6KFvknPRJQ/icon
import InstagramIcon from "./icons/PlasmicIcon__Instagram"; // plasmic-import: cci5PyA8P44/icon
import TwitterIcon from "./icons/PlasmicIcon__Twitter"; // plasmic-import: xoc1csyAe0f/icon
import IconsGeneralCartIcon from "./icons/PlasmicIcon__IconsGeneralCart"; // plasmic-import: 9ZCxifYqRZR/icon

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  mntn?: p.Flex<"div">;
  hg?: p.Flex<"div">;
  bgHero?: p.Flex<"div">;
  content?: p.Flex<"div">;
  group17?: p.Flex<"div">;
  rectangle21?: p.Flex<"div">;
  group7?: p.Flex<"div">;
  equipment?: p.Flex<"div">;
  mg?: p.Flex<"div">;
  vg?: p.Flex<"div">;
  bgContent?: p.Flex<"div">;
  slider?: p.Flex<"div">;
  slider2?: p.Flex<"div">;
  sliderBg?: p.Flex<"div">;
  sliderIndicator?: p.Flex<"div">;
  text?: p.Flex<"div">;
  frame1?: p.Flex<"div">;
  header?: p.Flex<"div">;
  logo?: p.Flex<"div">;
  content2?: p.Flex<"div">;
  content3?: p.Flex<"div">;
  equipment2?: p.Flex<"div">;
  _01?: p.Flex<"div">;
  content4?: p.Flex<"div">;
  tagline?: p.Flex<"div">;
  line?: p.Flex<"div">;
  determiningWhatLevelOfHikerYouAreCanBeAnImportantToolWhenPlanningFutureHikesThisHikingLevelGuideWillHelpYouPlanHikesAccordingToDifferentHikeRatingsSetByVariousWebsitesLikeAllTrailsAndModernHikerWhatTypeOfHikerAreYouNoviceModerateAdvancedModerateExpertOrExpertBackpacker?: p.Flex<"div">;
  more?: p.Flex<"div">;
  equipment3?: p.Flex<"div">;
  content5?: p.Flex<"div">;
  _012?: p.Flex<"div">;
  equipment4?: p.Flex<"div">;
  content6?: p.Flex<"div">;
  tagline2?: p.Flex<"div">;
  line2?: p.Flex<"div">;
  more2?: p.Flex<"div">;
  equipment5?: p.Flex<"div">;
  content7?: p.Flex<"div">;
  equipment6?: p.Flex<"div">;
  _013?: p.Flex<"div">;
  content8?: p.Flex<"div">;
  tagline3?: p.Flex<"div">;
  line3?: p.Flex<"div">;
  more3?: p.Flex<"div">;
  equipment7?: p.Flex<"div">;
  footer?: p.Flex<"div">;
  logo2?: p.Flex<"div">;
  links?: p.Flex<"div">;
  links2?: p.Flex<"div">;
};

export interface DefaultHomepageProps {
  className?: string;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
        <meta key="og:title" property="og:title" content={""} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"mntn"}
            data-plasmic-override={overrides.mntn}
            className={classNames(defaultcss.all, sty.mntn)}
          >
            <div
              data-plasmic-name={"hg"}
              data-plasmic-override={overrides.hg}
              className={classNames(defaultcss.all, sty.hg)}
            />

            <div
              data-plasmic-name={"bgHero"}
              data-plasmic-override={overrides.bgHero}
              className={classNames(defaultcss.all, sty.bgHero)}
            />

            <p.Stack
              as={"div"}
              data-plasmic-name={"content"}
              data-plasmic-override={overrides.content}
              hasGap={true}
              className={classNames(defaultcss.all, sty.content)}
            >
              <div
                data-plasmic-name={"group17"}
                data-plasmic-override={overrides.group17}
                className={classNames(defaultcss.all, sty.group17)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__g8D9M
                  )}
                >
                  {"A Hiking guide"}
                </div>

                <div
                  data-plasmic-name={"rectangle21"}
                  data-plasmic-override={overrides.rectangle21}
                  className={classNames(defaultcss.all, sty.rectangle21)}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__ubfgp
                )}
              >
                {"Be prepared for the Mountains and beyond!"}
              </div>

              <div
                data-plasmic-name={"group7"}
                data-plasmic-override={overrides.group7}
                className={classNames(defaultcss.all, sty.group7)}
              >
                <div
                  data-plasmic-name={"equipment"}
                  data-plasmic-override={overrides.equipment}
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.equipment
                  )}
                >
                  {"scroll down"}
                </div>

                <IconnavigationarrowDownward24PxIcon
                  className={classNames(defaultcss.all, sty.svg___0GkWb)}
                  role={"img"}
                />
              </div>
            </p.Stack>

            <div
              data-plasmic-name={"mg"}
              data-plasmic-override={overrides.mg}
              className={classNames(defaultcss.all, sty.mg)}
            />

            <div
              data-plasmic-name={"vg"}
              data-plasmic-override={overrides.vg}
              className={classNames(defaultcss.all, sty.vg)}
            />

            <div
              data-plasmic-name={"bgContent"}
              data-plasmic-override={overrides.bgContent}
              className={classNames(defaultcss.all, sty.bgContent)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__pBsG
              )}
            >
              {"Follow us"}
            </div>

            <InstagramIcon
              className={classNames(defaultcss.all, sty.svg__jybas)}
              role={"img"}
            />

            <TwitterIcon
              className={classNames(defaultcss.all, sty.svg__xNQx)}
              role={"img"}
            />

            <div
              data-plasmic-name={"slider"}
              data-plasmic-override={overrides.slider}
              className={classNames(defaultcss.all, sty.slider)}
            >
              <div
                data-plasmic-name={"slider2"}
                data-plasmic-override={overrides.slider2}
                className={classNames(defaultcss.all, sty.slider2)}
              >
                <div
                  data-plasmic-name={"sliderBg"}
                  data-plasmic-override={overrides.sliderBg}
                  className={classNames(defaultcss.all, sty.sliderBg)}
                />

                <div
                  data-plasmic-name={"sliderIndicator"}
                  data-plasmic-override={overrides.sliderIndicator}
                  className={classNames(defaultcss.all, sty.sliderIndicator)}
                />
              </div>

              <div
                data-plasmic-name={"text"}
                data-plasmic-override={overrides.text}
                className={classNames(defaultcss.all, sty.text)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame1"}
                  data-plasmic-override={overrides.frame1}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.frame1)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__hV3Nz
                    )}
                  >
                    {"Start"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__otf3I
                    )}
                  >
                    {"01"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__gSw2Y
                    )}
                  >
                    {"02"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__et5Iz
                    )}
                  >
                    {"03"}
                  </div>
                </p.Stack>
              </div>
            </div>

            <div
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames(defaultcss.all, sty.header)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__cUHh
                )}
              >
                {"Blog"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__twOgw
                )}
              >
                {"About us"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__aqkhH
                )}
              >
                {"Equipment"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__rcdUf
                )}
              >
                {"Account"}
              </div>

              <IconsGeneralCartIcon
                className={classNames(defaultcss.all, sty.svg__dRfgC)}
                role={"img"}
              />

              <div
                data-plasmic-name={"logo"}
                data-plasmic-override={overrides.logo}
                className={classNames(defaultcss.all, sty.logo)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__epMnD
                  )}
                >
                  {"M"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__dw6Y7
                  )}
                >
                  {"N"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__xur7
                  )}
                >
                  {"T"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__xPzhu
                  )}
                >
                  {"N"}
                </div>
              </div>
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"content2"}
              data-plasmic-override={overrides.content2}
              hasGap={true}
              className={classNames(defaultcss.all, sty.content2)}
            >
              <div
                data-plasmic-name={"content3"}
                data-plasmic-override={overrides.content3}
                className={classNames(defaultcss.all, sty.content3)}
              >
                <div
                  data-plasmic-name={"equipment2"}
                  data-plasmic-override={overrides.equipment2}
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.equipment2
                  )}
                >
                  {"01"}
                </div>

                <div
                  data-plasmic-name={"_01"}
                  data-plasmic-override={overrides._01}
                  className={classNames(defaultcss.all, sty._01)}
                />

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"content4"}
                  data-plasmic-override={overrides.content4}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.content4)}
                >
                  <div
                    data-plasmic-name={"tagline"}
                    data-plasmic-override={overrides.tagline}
                    className={classNames(defaultcss.all, sty.tagline)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__fMjo8
                      )}
                    >
                      {"GEt Started"}
                    </div>

                    <div
                      data-plasmic-name={"line"}
                      data-plasmic-override={overrides.line}
                      className={classNames(defaultcss.all, sty.line)}
                    />
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__pm2Xf
                    )}
                  >
                    {"What level of  hiker are you?"}
                  </div>

                  <div
                    data-plasmic-name={
                      "determiningWhatLevelOfHikerYouAreCanBeAnImportantToolWhenPlanningFutureHikesThisHikingLevelGuideWillHelpYouPlanHikesAccordingToDifferentHikeRatingsSetByVariousWebsitesLikeAllTrailsAndModernHikerWhatTypeOfHikerAreYouNoviceModerateAdvancedModerateExpertOrExpertBackpacker"
                    }
                    data-plasmic-override={
                      overrides.determiningWhatLevelOfHikerYouAreCanBeAnImportantToolWhenPlanningFutureHikesThisHikingLevelGuideWillHelpYouPlanHikesAccordingToDifferentHikeRatingsSetByVariousWebsitesLikeAllTrailsAndModernHikerWhatTypeOfHikerAreYouNoviceModerateAdvancedModerateExpertOrExpertBackpacker
                    }
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.determiningWhatLevelOfHikerYouAreCanBeAnImportantToolWhenPlanningFutureHikesThisHikingLevelGuideWillHelpYouPlanHikesAccordingToDifferentHikeRatingsSetByVariousWebsitesLikeAllTrailsAndModernHikerWhatTypeOfHikerAreYouNoviceModerateAdvancedModerateExpertOrExpertBackpacker
                    )}
                  >
                    {
                      "Determining what level of hiker you are can be an important tool when planning future hikes. This hiking level guide will help you plan hikes according to different hike ratings set by various websites like All Trails and Modern Hiker. What type of hiker are you – novice, moderate, advanced moderate, expert, or expert backpacker? "
                    }
                  </div>

                  <div
                    data-plasmic-name={"more"}
                    data-plasmic-override={overrides.more}
                    className={classNames(defaultcss.all, sty.more)}
                  >
                    <div
                      data-plasmic-name={"equipment3"}
                      data-plasmic-override={overrides.equipment3}
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.equipment3
                      )}
                    >
                      {"read more"}
                    </div>

                    <IconnavigationarrowDownward24PxIcon
                      className={classNames(defaultcss.all, sty.svg__dbRXg)}
                      role={"img"}
                    />
                  </div>
                </p.Stack>
              </div>

              <div
                data-plasmic-name={"content5"}
                data-plasmic-override={overrides.content5}
                className={classNames(defaultcss.all, sty.content5)}
              >
                <div
                  data-plasmic-name={"_012"}
                  data-plasmic-override={overrides._012}
                  className={classNames(defaultcss.all, sty._012)}
                />

                <div
                  data-plasmic-name={"equipment4"}
                  data-plasmic-override={overrides.equipment4}
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.equipment4
                  )}
                >
                  {"02"}
                </div>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"content6"}
                  data-plasmic-override={overrides.content6}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.content6)}
                >
                  <div
                    data-plasmic-name={"tagline2"}
                    data-plasmic-override={overrides.tagline2}
                    className={classNames(defaultcss.all, sty.tagline2)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__iCqAo
                      )}
                    >
                      {"Hiking Essentials"}
                    </div>

                    <div
                      data-plasmic-name={"line2"}
                      data-plasmic-override={overrides.line2}
                      className={classNames(defaultcss.all, sty.line2)}
                    />
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__vns4X
                    )}
                  >
                    {"Picking the right Hiking Gear!"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__xcFkm
                    )}
                  >
                    {
                      "The nice thing about beginning hiking is that you don’t really need any special gear, you can probably get away with things you already have.\nLet’s start with clothing. A typical mistake hiking beginners make is wearing jeans and regular clothes, which will get heavy and chafe wif they get sweaty or wet."
                    }
                  </div>

                  <div
                    data-plasmic-name={"more2"}
                    data-plasmic-override={overrides.more2}
                    className={classNames(defaultcss.all, sty.more2)}
                  >
                    <div
                      data-plasmic-name={"equipment5"}
                      data-plasmic-override={overrides.equipment5}
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.equipment5
                      )}
                    >
                      {"read more"}
                    </div>

                    <IconnavigationarrowDownward24PxIcon
                      className={classNames(defaultcss.all, sty.svg__iYrLu)}
                      role={"img"}
                    />
                  </div>
                </p.Stack>
              </div>

              <div
                data-plasmic-name={"content7"}
                data-plasmic-override={overrides.content7}
                className={classNames(defaultcss.all, sty.content7)}
              >
                <div
                  data-plasmic-name={"equipment6"}
                  data-plasmic-override={overrides.equipment6}
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.equipment6
                  )}
                >
                  {"03"}
                </div>

                <div
                  data-plasmic-name={"_013"}
                  data-plasmic-override={overrides._013}
                  className={classNames(defaultcss.all, sty._013)}
                />

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"content8"}
                  data-plasmic-override={overrides.content8}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.content8)}
                >
                  <div
                    data-plasmic-name={"tagline3"}
                    data-plasmic-override={overrides.tagline3}
                    className={classNames(defaultcss.all, sty.tagline3)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__h06Mm
                      )}
                    >
                      {"where you go is the key"}
                    </div>

                    <div
                      data-plasmic-name={"line3"}
                      data-plasmic-override={overrides.line3}
                      className={classNames(defaultcss.all, sty.line3)}
                    />
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__uprPs
                    )}
                  >
                    {"Understand Your Map & Timing"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__otXag
                    )}
                  >
                    {
                      "To start, print out the hiking guide and map. If it’s raining, throw them in a Zip-Lock bag. Read over the guide, study the map, and have a good idea of what to expect. I like to know what my next landmark is as I hike. For example, I’ll read the guide and know that say, in a mile, I make a right turn at the junction.."
                    }
                  </div>

                  <div
                    data-plasmic-name={"more3"}
                    data-plasmic-override={overrides.more3}
                    className={classNames(defaultcss.all, sty.more3)}
                  >
                    <div
                      data-plasmic-name={"equipment7"}
                      data-plasmic-override={overrides.equipment7}
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.equipment7
                      )}
                    >
                      {"read more"}
                    </div>

                    <IconnavigationarrowDownward24PxIcon
                      className={classNames(defaultcss.all, sty.svg__eBzCb)}
                      role={"img"}
                    />
                  </div>
                </p.Stack>
              </div>

              <div
                data-plasmic-name={"footer"}
                data-plasmic-override={overrides.footer}
                className={classNames(defaultcss.all, sty.footer)}
              >
                <div
                  data-plasmic-name={"logo2"}
                  data-plasmic-override={overrides.logo2}
                  className={classNames(defaultcss.all, sty.logo2)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___03Ur0
                    )}
                  >
                    {"M"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___5NPvu
                    )}
                  >
                    {"N"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__zT4Uk
                    )}
                  >
                    {"T"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__tJ4HK
                    )}
                  >
                    {"N"}
                  </div>
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__dvpHj
                  )}
                >
                  {
                    "Get out there & discover your next slope, mountain & destination!"
                  }
                </div>

                <div
                  data-plasmic-name={"links"}
                  data-plasmic-override={overrides.links}
                  className={classNames(defaultcss.all, sty.links)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___8L3Q7
                    )}
                  >
                    {"More on The Blog"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__zoECm
                    )}
                  >
                    {"About MNTN"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___1RtkX
                    )}
                  >
                    {"Contributors & Writers"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__gdMfa
                    )}
                  >
                    {"Write For Us"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__gkuDr
                    )}
                  >
                    {"Contact Us"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__rXqQd
                    )}
                  >
                    {"Privacy Policy"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"links2"}
                  data-plasmic-override={overrides.links2}
                  className={classNames(defaultcss.all, sty.links2)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__tqAs3
                    )}
                  >
                    {"More on MNTN"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__aD6N
                    )}
                  >
                    {"The Team"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__sLv4F
                    )}
                  >
                    {"Jobs"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__inCmB
                    )}
                  >
                    {"Press"}
                  </div>
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__v6IJ
                  )}
                >
                  {"Copyright 2019 MNTN, Inc. Terms & Privacy"}
                </div>
              </div>
            </p.Stack>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "mntn",
    "hg",
    "bgHero",
    "content",
    "group17",
    "rectangle21",
    "group7",
    "equipment",
    "mg",
    "vg",
    "bgContent",
    "slider",
    "slider2",
    "sliderBg",
    "sliderIndicator",
    "text",
    "frame1",
    "header",
    "logo",
    "content2",
    "content3",
    "equipment2",
    "_01",
    "content4",
    "tagline",
    "line",
    "determiningWhatLevelOfHikerYouAreCanBeAnImportantToolWhenPlanningFutureHikesThisHikingLevelGuideWillHelpYouPlanHikesAccordingToDifferentHikeRatingsSetByVariousWebsitesLikeAllTrailsAndModernHikerWhatTypeOfHikerAreYouNoviceModerateAdvancedModerateExpertOrExpertBackpacker",
    "more",
    "equipment3",
    "content5",
    "_012",
    "equipment4",
    "content6",
    "tagline2",
    "line2",
    "more2",
    "equipment5",
    "content7",
    "equipment6",
    "_013",
    "content8",
    "tagline3",
    "line3",
    "more3",
    "equipment7",
    "footer",
    "logo2",
    "links",
    "links2"
  ],
  mntn: [
    "mntn",
    "hg",
    "bgHero",
    "content",
    "group17",
    "rectangle21",
    "group7",
    "equipment",
    "mg",
    "vg",
    "bgContent",
    "slider",
    "slider2",
    "sliderBg",
    "sliderIndicator",
    "text",
    "frame1",
    "header",
    "logo",
    "content2",
    "content3",
    "equipment2",
    "_01",
    "content4",
    "tagline",
    "line",
    "determiningWhatLevelOfHikerYouAreCanBeAnImportantToolWhenPlanningFutureHikesThisHikingLevelGuideWillHelpYouPlanHikesAccordingToDifferentHikeRatingsSetByVariousWebsitesLikeAllTrailsAndModernHikerWhatTypeOfHikerAreYouNoviceModerateAdvancedModerateExpertOrExpertBackpacker",
    "more",
    "equipment3",
    "content5",
    "_012",
    "equipment4",
    "content6",
    "tagline2",
    "line2",
    "more2",
    "equipment5",
    "content7",
    "equipment6",
    "_013",
    "content8",
    "tagline3",
    "line3",
    "more3",
    "equipment7",
    "footer",
    "logo2",
    "links",
    "links2"
  ],
  hg: ["hg"],
  bgHero: ["bgHero"],
  content: ["content", "group17", "rectangle21", "group7", "equipment"],
  group17: ["group17", "rectangle21"],
  rectangle21: ["rectangle21"],
  group7: ["group7", "equipment"],
  equipment: ["equipment"],
  mg: ["mg"],
  vg: ["vg"],
  bgContent: ["bgContent"],
  slider: [
    "slider",
    "slider2",
    "sliderBg",
    "sliderIndicator",
    "text",
    "frame1"
  ],
  slider2: ["slider2", "sliderBg", "sliderIndicator"],
  sliderBg: ["sliderBg"],
  sliderIndicator: ["sliderIndicator"],
  text: ["text", "frame1"],
  frame1: ["frame1"],
  header: ["header", "logo"],
  logo: ["logo"],
  content2: [
    "content2",
    "content3",
    "equipment2",
    "_01",
    "content4",
    "tagline",
    "line",
    "determiningWhatLevelOfHikerYouAreCanBeAnImportantToolWhenPlanningFutureHikesThisHikingLevelGuideWillHelpYouPlanHikesAccordingToDifferentHikeRatingsSetByVariousWebsitesLikeAllTrailsAndModernHikerWhatTypeOfHikerAreYouNoviceModerateAdvancedModerateExpertOrExpertBackpacker",
    "more",
    "equipment3",
    "content5",
    "_012",
    "equipment4",
    "content6",
    "tagline2",
    "line2",
    "more2",
    "equipment5",
    "content7",
    "equipment6",
    "_013",
    "content8",
    "tagline3",
    "line3",
    "more3",
    "equipment7",
    "footer",
    "logo2",
    "links",
    "links2"
  ],
  content3: [
    "content3",
    "equipment2",
    "_01",
    "content4",
    "tagline",
    "line",
    "determiningWhatLevelOfHikerYouAreCanBeAnImportantToolWhenPlanningFutureHikesThisHikingLevelGuideWillHelpYouPlanHikesAccordingToDifferentHikeRatingsSetByVariousWebsitesLikeAllTrailsAndModernHikerWhatTypeOfHikerAreYouNoviceModerateAdvancedModerateExpertOrExpertBackpacker",
    "more",
    "equipment3"
  ],
  equipment2: ["equipment2"],
  _01: ["_01"],
  content4: [
    "content4",
    "tagline",
    "line",
    "determiningWhatLevelOfHikerYouAreCanBeAnImportantToolWhenPlanningFutureHikesThisHikingLevelGuideWillHelpYouPlanHikesAccordingToDifferentHikeRatingsSetByVariousWebsitesLikeAllTrailsAndModernHikerWhatTypeOfHikerAreYouNoviceModerateAdvancedModerateExpertOrExpertBackpacker",
    "more",
    "equipment3"
  ],
  tagline: ["tagline", "line"],
  line: ["line"],
  determiningWhatLevelOfHikerYouAreCanBeAnImportantToolWhenPlanningFutureHikesThisHikingLevelGuideWillHelpYouPlanHikesAccordingToDifferentHikeRatingsSetByVariousWebsitesLikeAllTrailsAndModernHikerWhatTypeOfHikerAreYouNoviceModerateAdvancedModerateExpertOrExpertBackpacker: [
    "determiningWhatLevelOfHikerYouAreCanBeAnImportantToolWhenPlanningFutureHikesThisHikingLevelGuideWillHelpYouPlanHikesAccordingToDifferentHikeRatingsSetByVariousWebsitesLikeAllTrailsAndModernHikerWhatTypeOfHikerAreYouNoviceModerateAdvancedModerateExpertOrExpertBackpacker"
  ],
  more: ["more", "equipment3"],
  equipment3: ["equipment3"],
  content5: [
    "content5",
    "_012",
    "equipment4",
    "content6",
    "tagline2",
    "line2",
    "more2",
    "equipment5"
  ],
  _012: ["_012"],
  equipment4: ["equipment4"],
  content6: ["content6", "tagline2", "line2", "more2", "equipment5"],
  tagline2: ["tagline2", "line2"],
  line2: ["line2"],
  more2: ["more2", "equipment5"],
  equipment5: ["equipment5"],
  content7: [
    "content7",
    "equipment6",
    "_013",
    "content8",
    "tagline3",
    "line3",
    "more3",
    "equipment7"
  ],
  equipment6: ["equipment6"],
  _013: ["_013"],
  content8: ["content8", "tagline3", "line3", "more3", "equipment7"],
  tagline3: ["tagline3", "line3"],
  line3: ["line3"],
  more3: ["more3", "equipment7"],
  equipment7: ["equipment7"],
  footer: ["footer", "logo2", "links", "links2"],
  logo2: ["logo2"],
  links: ["links"],
  links2: ["links2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  mntn: "div";
  hg: "div";
  bgHero: "div";
  content: "div";
  group17: "div";
  rectangle21: "div";
  group7: "div";
  equipment: "div";
  mg: "div";
  vg: "div";
  bgContent: "div";
  slider: "div";
  slider2: "div";
  sliderBg: "div";
  sliderIndicator: "div";
  text: "div";
  frame1: "div";
  header: "div";
  logo: "div";
  content2: "div";
  content3: "div";
  equipment2: "div";
  _01: "div";
  content4: "div";
  tagline: "div";
  line: "div";
  determiningWhatLevelOfHikerYouAreCanBeAnImportantToolWhenPlanningFutureHikesThisHikingLevelGuideWillHelpYouPlanHikesAccordingToDifferentHikeRatingsSetByVariousWebsitesLikeAllTrailsAndModernHikerWhatTypeOfHikerAreYouNoviceModerateAdvancedModerateExpertOrExpertBackpacker: "div";
  more: "div";
  equipment3: "div";
  content5: "div";
  _012: "div";
  equipment4: "div";
  content6: "div";
  tagline2: "div";
  line2: "div";
  more2: "div";
  equipment5: "div";
  content7: "div";
  equipment6: "div";
  _013: "div";
  content8: "div";
  tagline3: "div";
  line3: "div";
  more3: "div";
  equipment7: "div";
  footer: "div";
  logo2: "div";
  links: "div";
  links2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicHomepage__VariantsArgs;
  args?: PlasmicHomepage__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    mntn: makeNodeComponent("mntn"),
    hg: makeNodeComponent("hg"),
    bgHero: makeNodeComponent("bgHero"),
    content: makeNodeComponent("content"),
    group17: makeNodeComponent("group17"),
    rectangle21: makeNodeComponent("rectangle21"),
    group7: makeNodeComponent("group7"),
    equipment: makeNodeComponent("equipment"),
    mg: makeNodeComponent("mg"),
    vg: makeNodeComponent("vg"),
    bgContent: makeNodeComponent("bgContent"),
    slider: makeNodeComponent("slider"),
    slider2: makeNodeComponent("slider2"),
    sliderBg: makeNodeComponent("sliderBg"),
    sliderIndicator: makeNodeComponent("sliderIndicator"),
    text: makeNodeComponent("text"),
    frame1: makeNodeComponent("frame1"),
    header: makeNodeComponent("header"),
    logo: makeNodeComponent("logo"),
    content2: makeNodeComponent("content2"),
    content3: makeNodeComponent("content3"),
    equipment2: makeNodeComponent("equipment2"),
    _01: makeNodeComponent("_01"),
    content4: makeNodeComponent("content4"),
    tagline: makeNodeComponent("tagline"),
    line: makeNodeComponent("line"),
    determiningWhatLevelOfHikerYouAreCanBeAnImportantToolWhenPlanningFutureHikesThisHikingLevelGuideWillHelpYouPlanHikesAccordingToDifferentHikeRatingsSetByVariousWebsitesLikeAllTrailsAndModernHikerWhatTypeOfHikerAreYouNoviceModerateAdvancedModerateExpertOrExpertBackpacker: makeNodeComponent(
      "determiningWhatLevelOfHikerYouAreCanBeAnImportantToolWhenPlanningFutureHikesThisHikingLevelGuideWillHelpYouPlanHikesAccordingToDifferentHikeRatingsSetByVariousWebsitesLikeAllTrailsAndModernHikerWhatTypeOfHikerAreYouNoviceModerateAdvancedModerateExpertOrExpertBackpacker"
    ),
    more: makeNodeComponent("more"),
    equipment3: makeNodeComponent("equipment3"),
    content5: makeNodeComponent("content5"),
    _012: makeNodeComponent("_012"),
    equipment4: makeNodeComponent("equipment4"),
    content6: makeNodeComponent("content6"),
    tagline2: makeNodeComponent("tagline2"),
    line2: makeNodeComponent("line2"),
    more2: makeNodeComponent("more2"),
    equipment5: makeNodeComponent("equipment5"),
    content7: makeNodeComponent("content7"),
    equipment6: makeNodeComponent("equipment6"),
    _013: makeNodeComponent("_013"),
    content8: makeNodeComponent("content8"),
    tagline3: makeNodeComponent("tagline3"),
    line3: makeNodeComponent("line3"),
    more3: makeNodeComponent("more3"),
    equipment7: makeNodeComponent("equipment7"),
    footer: makeNodeComponent("footer"),
    logo2: makeNodeComponent("logo2"),
    links: makeNodeComponent("links"),
    links2: makeNodeComponent("links2"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
